# Generated by Django 3.2.5 on 2023-03-31 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverfile',
            name='content',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='serverfile',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='serverfile',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='serverfile',
            name='size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='serverfile',
            name='name',
            field=models.CharField(blank=True, default='新的文件', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='serverfile',
            name='path',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='serverfile',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='game_server.server'),
        ),
    ]
