# Generated by Django 3.2.5 on 2023-04-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_server', '0003_auto_20230331_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='private_key_password',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
