# Generated by Django 3.2.5 on 2023-04-03 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_server', '0004_server_private_key_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('lastrun', models.DateTimeField(blank=True, null=True)),
                ('lastresult', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
