# Generated by Django 3.2.5 on 2023-04-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_server', '0006_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='action',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
